scikit-hep/root_numpy

root_numpy/src/TreeChain.h
root_numpy/tests.py

Don't bother remember and revert to original branch status, and avoid the slow SetBranchStatus.
Tested on a tree with 2256 branches.
Before:
```python
>>> min(timeit.Timer("rnp.tree2array(t, branches=branches)", setup=setup).repeat(10, 1))
14.4979131222
```
After:
```python
>>> min(timeit.Timer("rnp.tree2array(t, branches=branches)", setup=setup).repeat(10, 1))
0.362231016159
```

[MRG] Huge speed improvement for trees with many branches

---

root_numpy/_utils.py
root_numpy/tests.py

[MRG] stretch() improvements

---

root_numpy/info.py
root_numpy/src/_librootnumpy.cpp
root_numpy/src/tree.pyx

Example:
```
>>> from rootpy.io import root_open
>>> from root_numpy import tree2array
>>> f = root_open('/afs/cern.ch/user/q/qbuat/work/public/xtau_output/hadhad/v1/hhskim/hhskim.root')
>>> tree2array(f['PowhegPythiaEvtGen_P2012_ttbar_hdamp172p5_nonallhad'])
MemoryError: failed to allocate memory for 36.3 GB array of 14386982 records with 394 fields
```

[MRG] tree2array: more informative MemoryError

---

root_numpy/src/TreeChain.h
root_numpy/src/root_numpy.pxi

[MRG] long -> long long

---

root_numpy/_tree.py
root_numpy/src/Column.h
root_numpy/src/TreeChain.h
root_numpy/src/_librootnumpy.cpp
root_numpy/src/root_numpy.pxi
root_numpy/src/tree.pyx

Without caching:
```
bytes read:  640659
read calls:  2604
```
With a 1MB cache:
```
Number of branches in the cache ...: 100
Cache Efficiency ..................: 1.000000
Cache Efficiency Rel...............: 1.000000
Learn entries......................: 100
Cached Reading.....................: 623600 bytes in 1 transactions
Reading............................: 0 bytes in 0 uncached transactions
Readahead..........................: 256000 bytes with overhead = 0 bytes
Average transaction................: 623.600000 Kbytes
Number of blocks in current cache..: 2600, total size: 623600
```

[MRG] tree2array: enable tree caching and add cache_size argument

---

Makefile
root_numpy/_tree.py
root_numpy/src/ROOT.pxi
root_numpy/src/TreeChain.h
root_numpy/src/_librootnumpy.cpp
root_numpy/src/root_numpy.pxi
root_numpy/src/tree.pyx
root_numpy/tmva/src/_libtmvanumpy.cpp

Provide an option to warn if a tree is missing from an input file istead of raising an IOError.
This is more convenient when globbing many files and some don't contain the requested tree due to how your production system operates (thinking of you, ATLAS...)

[MRG] warn_missing_tree

---

root_numpy/_utils.py
root_numpy/tests.py

When using `stretch`, information about the array index is lost in the stretched record array.
It would be nice if we could retain that information with an optional argument like implemented in this PR.
When `return_indices=True`, `stretch` returns an index array in addition to the structured array.
An alternative would be to store the information in a new field in the structured array, but here we would have to assume a name for that field, and users might not expect their array to gain a new field when ~~calling the function~~ supplying the optional argument.

Add optional return_indices argument to stretch

---

docs/install.rst
root_numpy/_hist.py
root_numpy/info.py
root_numpy/src/ROOT.pxi
root_numpy/src/_librootnumpy.cpp
root_numpy/src/hist.pyx
root_numpy/tests.py

As requested by @cbourjau in #188 this PR adds support for THn and THnSparse (with #arbitrary dimensionality) in hist2array:
```python
>>> from root_numpy import array2hist, hist2array
>>> import numpy as np
>>> from rootpy.plotting import Hist2D
>>> hist = Hist2D(5, 0, 1, 3, 0, 1, type='F')
>>> array = np.random.randint(0, 10, size=(7, 5))
>>> array
array([[0, 4, 3, 5, 2],
[2, 4, 4, 1, 2],
[8, 1, 3, 4, 8],
[1, 3, 0, 2, 3],
[1, 8, 5, 6, 8],
[4, 7, 8, 4, 5],
[8, 7, 1, 4, 5]])
>>> array2hist(array, hist)
Hist2D('Hist2D_EJWHJJNmSmHPVeeiWtzFkT')
>>> hist2array(hist)
array([[ 4.,  4.,  1.],
[ 1.,  3.,  4.],
[ 3.,  0.,  2.],
[ 8.,  5.,  6.],
[ 7.,  8.,  4.]], dtype=float32)
>>> import ROOT
>>> hist2array(ROOT.THn.CreateHn("", "", hist))   # <=== same result
array([[ 4.,  4.,  1.],
[ 1.,  3., …
```

Support for THn and THnSparse in hist2array

---

root_numpy/__init__.py
root_numpy/_tree.py
root_numpy/_warnings.py

These functions will be removed in 4.5.0
```python
>>> from root_numpy import root2rec
>>> root2rec("root_numpy/testdata/single1.root")
root_numpy/_tree.py:236: DeprecationWarning: root2rec is deprecated and will be removed in 4.5.0. Instead use root2array(...).view(np.recarray)
DeprecationWarning)
rec.array([(1, 1.0, 1.0), (2, 3.0, 4.0), (3, 5.0, 7.0), (4, 7.0, 10.0),
(5, 9.0, 13.0), (6, 11.0, 16.0), (7, 13.0, 19.0), (8, 15.0, 22.0),
(9, 17.0, 25.0), (10, 19.0, 28.0), (11, 21.0, 31.0), (12, 23.0, 34.0),
(13, 25.0, 37.0), (14, 27.0, 40.0), (15, 29.0, 43.0), (16, 31.0, 46.0),
(17, 33.0, 49.0), (18, 35.0, 52.0), (19, 37.0, 55.0), (20, 39.0, 58.0),
...
```

[MRG] Add DeprecationWarnings for tree2rec and root2rec

---

.coveragerc
.gitignore
README.rst
docs/index.rst
root_numpy/__init__.py
root_numpy/setup_utils.py
setup.py

xref #136 
Installation now writes a config.json in root_numpy containing the ROOT and numpy versions present at install time. Then root_numpy will warn if current versions ever differ.

[WIP] Implement #136: Warn if current version of ROOT or NumPy is different than version built against

---

root_numpy/info.py
setup.py

xref #256 
``NOTMVA=1 pip install root_numpy``
This is a temporary solution until we can handle their new DataLoader interface in TMVA

disable building of TMVA interface if NOTMVA is set

---

root_numpy/_utils.py
root_numpy/tests.py

If the fields are scalars the shape of the output array will be ``(len(rec), num_fields)``. If the fields are arrays of length ``num_things`` the shape of the output array will be ``(len(rec), num_things, num_fields)``. 
```python
>>> from root_numpy import rec2array                                        
>>> import numpy as np                                                      
>>> a = np.array([                                                          
...         (12345, 2., 2.1, True),                                         
...         (3, 4., 4.2, False),],                                          
...         dtype=[                                                         
...             ('x', np.int32),                                            
...             ('y', …
```

rec2array: handle fixed-length 1D array fields

---

root_numpy/_utils.py
root_numpy/tests.py

Produce an unstructured 1D array if fields is a string. This doesn't change existing behaviour.

stretch: if fields is single string (not list) then flatten output

---

setup.py

* Add numpy to setup's extras_require to make explicit dependency optional:
Useful for a requirements.txt file with root_numpy[with-numpy]. Exactly how scikit-learn implements optional explicit dependency on numpy in setup.py: http://scikit-learn.org/stable/install.html
* Put numpy in setup's setup_requires and install_requires lists only if not already installed.
Prevents pip from upgrading an existing numpy installation.
This is what scipy does.

[MRG] numpy dependency in setup.py

---

AUTHORS.rst
MANIFEST.in

I prefer not to have a file listing names/emails and instead rely on the git history itself. It can sometimes be difficult to determine at what point someone has contributed enough to be listed as an "author" in this file. Better to just check the git history and get a sense of how much each committer has contributed:
https://github.com/scikit-hep/root_numpy/graphs/contributors

rm AUTHORS.rst

---

docs/contributing.rst
docs/faq.rst
docs/index.rst
docs/start.rst

DOCS: promote Contributing section to top-level 

---

.travis.yml

ROOT is now in the main `conda-forge` channel so that should be used instead of `chrisburr` and `conda-forge/label/gcc7`.

Use conda-forge's main channel for ROOT

---

root_numpy/setup_utils.py

`sys` is used by `setup_utils.py` but never imported

Add missing import

---

setup.py

Since pip 10 (released April 2018) this pip uses the `only-if-needed` policy by default.

Remove "prevent numpy upgrade" workaround

---

setup.py

Causes installation to fail with newer version of `numpy` (traceback below) and I'm not convinced it's needed.
```
Processing /Users/.../root_numpy_1574437817460/work
Created temporary directory: /private/var/folders/m4/ny3rx96n7j97182lb50mh8mc0000gn/T/pip-req-build-l8h7z4fa
Added file:///Users/.../root_numpy_1574437817460/work to build tracker '/private/var/folders/m4/ny3rx96n7j97182lb50mh8mc0000gn/T/pip-req-tracker-k_en1d3n'
Running setup.py (path:/private/var/folders/m4/ny3rx96n7j97182lb50mh8mc0000gn/T/pip-req-build-l8h7z4fa/setup.py) egg_info for package from file:///Users/.../root_numpy_1574437817460/work
Running command python setup.py egg_info
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/private/var/folders/m4/ny3rx96n7j97182lb50mh8mc0000gn/T/pip-re …
```

Don't delete os.link in setup.py
